const students = [
   
    {
        name: "MUBARIK SHEIKH HASSAN",
        password: "00215",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "62",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "71", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },
{
        name: "ABDI MAHAMED ABDI",
        password: "0011",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "76", 
                grade: "B+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "57",
                grade: "C"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "74", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "90",
                grade: "A+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            
           
         
        ],
    },
{
        name: "ABDIFATAH MOHAMED JAMA",
        password: "0019",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "68", 
                grade: "B-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "66",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "72", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },
{
        name: "ABDIRAYS ABDILE AFI",
        password: "0028",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "68",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },
{
        name: "ABDIWAHAB KAHIN ABDI",
        password: "0034",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "81", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "70",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "68.5", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "79",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "76",
                grade: "B+"},
            
           
         
        ],
    },

{
        name: "ABDULAHI ABDI DIES",
        password: "0035",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "90", 
                grade: "A+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "67.5",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "76", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "78",
                grade: "B+"},
            
           
         
        ],
    },


{
        name: "ABDULAHI ABDI HASSAN",
        password: "0036",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "46", 
                grade: "C-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "16",
                grade: "F"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "55", 
                grade: "C-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "60",
                grade: "C+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "100",
                grade: "A+"},
            
           
         
        ],
    },

{
        name: "ABDULAI IRSHAD SALAH",
        password: "0041",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "45", 
                grade: "C-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "62",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "85",
                grade: "A"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            
           
         
        ],
    },


{
        name: "ABDULAHI MOALIN ALI HAMUD",
        password: "0043",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "84", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "79",
                grade: "B+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "82", 
                grade: "A-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "ADE ARAB MAHAMED",
        password: "0050",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "0",
                grade: "NG"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },

{
        name: "ADAN MAHAMED ABDI",
        password: "0053",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "81", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "74",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "77.5", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "AHMED FARAH NUUR",
        password: "",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "0",
                grade: "NG"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },

{
        name: "ALI HASSAN JAMA",
        password: "0061",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "87", 
                grade: "A" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "49",
                grade: "C-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "63", 
                grade: "C+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },


{
        name: "AMAL YUSUF AMIR",
        password: "0065",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "69", 
                grade: "B-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "62",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "67", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            
           
         
        ],
    },

{
        name: "AMINO MUHUMED ADEN",
        password: "0067",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "67", 
                grade: "B-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "80",
                grade: "A-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "89.5", 
                grade: "A" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "79",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            
           
         
        ],
    },

{
        name: "BADRI MURSAL AHMED",
        password: "0078",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "80", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "80",
                grade: "A-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "81", 
                grade: "A-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "BASHIR HASSAN JAMA",
        password: "0082",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "0",
                grade: "NG"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },

{
        name: "DAHAB ARAB MAHAMUD",
        password: "0085",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "55", 
                grade: "C" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "76",
                grade: "B+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "66", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "90",
                grade: "A+"},
            
           
         
        ],
    },

{
        name: "DAHIR BASHIR MAHAMED",
        password: "0083",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "63", 
                grade: "C+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "46",
                grade: "C-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "61", 
                grade: "C+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "77",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            
           
         
        ],
    },

{
        name: "DEK ABDULAHI ABDI",
        password: "0087",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "0",
                grade: "NG"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },

{
        name: "DUNIYA SHEIKH ABDULAHI",
        password: "0095",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "65", 
                grade: "B-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "55",
                grade: "C"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "65.5", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "88",
                grade: "A"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "76",
                grade: "B+"},
            
           
         
        ],
    },


{
        name: "FADUMO MAHAMED WARDHERE",
        password: "00113",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "90", 
                grade: "A+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "77",
                grade: "B+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "86", 
                grade: "A" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "79",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "FADUMO SHAFEC KHALIF",
        password: "00116",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "74", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "68",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "71", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "95",
                grade: "A+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "FALIS JAMAL ABDISALAM",
        password: "0096",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "90", 
                grade: "A+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "70",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "83", 
                grade: "A-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "85",
                grade: "A"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "FARHAN MAHAMED MAHAMUD",
        password: "00105",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "90", 
                grade: "A+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "68",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "75", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "86",
                grade: "A"},
            
           
         
        ],
    },

{
        name: "FARHIYA ABDULAHI HUSSIEN",
        password: "00107",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "90", 
                grade: "A+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "71",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "88.5", 
                grade: "A" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "HADI AFI KORANE",
        password: "00121",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "78", 
                grade: "B+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "77.5",
                grade: "B+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "78", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "78",
                grade: "B+"},
            
           
         
        ],
    },


{
        name: "HAMDI ALI DAHIR",
        password: "00127",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "65", 
                grade: "B-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "66",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "73", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "69",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "90",
                grade: "A+"},
            
           
         
        ],
    },

{
        name: "HASSAN MAHAMED AHMED",
        password: "00134",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "87", 
                grade: "A" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "71",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "81", 
                grade: "A-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "HASSAN ABDI NUUR",
        password: "00131",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "64",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "69", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "78",
                grade: "B+"},
            
           
         
        ],
    },

{
        name: "HODAN DUBAD ADEN",
        password: "00143",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "75", 
                grade: "B+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "50",
                grade: "C"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "61", 
                grade: "C+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            
           
         
        ],
    },

{
        name: "HODAN MAHAMED OMER",
        password: "00144",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "80", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "49",
                grade: "C-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70.5", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "68",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "HUSSIEN DAKANE YUSUF",
        password: "00145",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "50", 
                grade: "C-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "62",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "69",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "",
        password: "",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "", 
                grade: "" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "",
                grade: ""},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "", 
                grade: "" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "",
                grade: ""},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "",
                grade: ""},
            
           
         
        ],
    },

{
        name: "IMAN MAHAMED BUKHARI",
        password: "00156",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "43", 
                grade: "D" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "10",
                grade: "F"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "30", 
                grade: "F" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "87",
                grade: "A"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "IKRO MAHAMED MUHUMED",
        password: "00153",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "75", 
                grade: "B+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "78",
                grade: "B+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "85", 
                grade: "A" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "68",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "IFRAH AHMED WAYRAH",
        password: "00149",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "36", 
                grade: "F" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "48",
                grade: "C-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "65.5", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "78",
                grade: "B+"},
            
           
         
        ],
    },

{
        name: "JABIR DOUBLE ABDILE",
        password: "00148",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "72", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "77",
                grade: "B+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "80.5", 
                grade: "A-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "65",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "81",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "JIMALE ALI SALAD",
        password: "00159",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "0",
                grade: "NG"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },

{
        name: "KOWSAR LAYL SOOYAAL",
        password: "00170",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "72",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "68", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "85",
                grade: "A"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "LAYLO MAHAMUD HIRSI",
        password: "00172",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "81", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "70",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "85", 
                grade: "A" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "79",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "MAHAMED IBRAHIM HAALAYS",
        password: "00197",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "87", 
                grade: "A" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "84",
                grade: "A-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "78", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "88",
                grade: "A"},
            
           
         
        ],
    },

{
        name: "MAHAMED YARRAW ADEN",
        password: "00211",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "67",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "63", 
                grade: "C+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "HASSAN WARDHER ABDI",
        password: "00137",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "0",
                grade: "NG"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },


{
        name: "MOHAMED YUSUF ADEN",
        password: "00212",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "0",
                grade: "NG"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "0", 
                grade: "NG" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "0",
                grade: "NG"},
            
           
         
        ],
    },

{
        name: "MAHAMED MAHAMUD HASSAN",
        password: "00205",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "85", 
                grade: "A" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "79",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "83", 
                grade: "A-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "85",
                grade: "A"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "78",
                grade: "B+"},
            
           
         
        ],
    },

{
        name: "MAHAMED ABDI ABDULAHI",
        password: "00183",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "90", 
                grade: "A+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "63",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "73", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "79",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "88",
                grade: "A"},
            
           
         
        ],
    },


{
        name: "MAHAMED ALI HAMZE",
        password: "00191",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "60",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "78.6", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "O",
                grade: "NG"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "88",
                grade: "A"},
            
           
         
        ],
    },

{
        name: "MAHAMED AYDID HASSAN",
        password: "00193",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "71", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "62.5",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "65",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },


{
        name: "MUMTAZ ADEN MAHAMUD",
        password: "00279",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "81", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "65",
                grade: "B-"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "72", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "90",
                grade: "A+"},
            
           
         
        ],
    },

{
        name: "NAJIB NOUR SAYID",
        password: "00220",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "55", 
                grade: "C" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "61",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "74", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "NAJMO ABDI DIRIYE",
        password: "00266",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "70", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "60",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "74.5", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "65",
                grade: "B-"},
            
           
         
        ],
    },

{
        name: "NASRO KHALID BASHIR",
        password: "00223",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "87", 
                grade: "A" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "71",
                grade: "B"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "73", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "NESTEHO JAMA GEDI",
        password: "00226",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "71", 
                grade: "B" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "59.7",
                grade: "C"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "76", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "WARIS MAHAD GARAD",
        password: "00273",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "84", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "76",
                grade: "B+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "79", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "60",
                grade: "C+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "85",
                grade: "A"},
            
           
         
        ],
    },

{
        name: "AMIN NOUR ABDULAHI",
        password: "00281",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "40", 
                grade: "C-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "56",
                grade: "C"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "75", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "66",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            
           
         
        ],
    },

{
        name: "ASHIA ABDULAHI IBRAHIM",
        password: "00280",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "50", 
                grade: "C" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "62.5",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "68", 
                grade: "B-" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "75",
                grade: "B+"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "66",
                grade: "B-"},
            
           
         
        ],
    },

{
        name: "MISKI MUHUMED ALI",
        password: "00282",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "78", 
                grade: "B+" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "60.5",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "79", 
                grade: "B+" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "80",
                grade: "A-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "85",
                grade: "A"},
            
           
         
        ],
    },

{
        name: "ABDI MOHAMED BARUD",
        password: "0042",
        department: "Bsc-nurse",
        creditHours: 19,
        courses: [
            { code: "DET", 
                name: "DETERMINANT", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "81", 
                grade: "A-" },
            { code: "REP", 
                name: "REPRODUCTIVE", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 7,  
                total: "64.5",
                grade: "C+"},
            { code: "NUT", 
                name: "NUTRITION", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3, 
                total: "72.5", 
                grade: "B" },
            { code: "nurs", 
                name: "BIOSTATICS", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "65",
                grade: "B-"},
            { code: "ENTR", 
                name: "en/ship", 
                year: "YEAR 4", 
                semester: "1", 
                academicYear: "2017", 
                credit: 3,
                total: "70",
                grade: "B"},
            
           
         
        ],
    },

// Add more student objects
];

document.getElementById("loginButton").addEventListener("click", function() {
    const name = document.getElementById("studentName").value;
    const password = document.getElementById("studentPassword").value;
    const errorMessage = document.getElementById("errorMessage");

    // Convert both input and student names to lowercase for case-insensitive comparison
    const student = students.find(s => s.name.toLowerCase() === name.toLowerCase() && s.password === password);

    if (student) {
        displayStudentInfo(student);
        document.getElementById("studentInfo").style.display = "block";
        errorMessage.style.display = "none"; // Hide error message if login successful
    } else {
        errorMessage.textContent = "waa khalad xogta aad galisey fadlan si sax ah u qor.";
        errorMessage.style.display = "block"; // Show error message
        document.getElementById("studentInfo").style.display = "none"; // Hide student info
    }
});

function displayStudentInfo(student) {
    // Display student name and ID
    document.getElementById("studentDisplayName").textContent = "" + student.name;
    document.getElementById("department").textContent = "" + student.department;
  

    const tableBody = document.getElementById("studentTableBody");
    tableBody.innerHTML = ""; // Clear previous data

    student.courses.forEach(course => {
        const row = document.createElement("tr");

        const codeCell = document.createElement("td");
        codeCell.textContent = course.code;
        row.appendChild(codeCell);

        const nameCell = document.createElement("td");
        nameCell.textContent = course.name;
        row.appendChild(nameCell);

        const yearCell = document.createElement("td");
        yearCell.textContent = course.year;
        row.appendChild(yearCell);

        const semesterCell = document.createElement("td");
        semesterCell.textContent = course.semester;
        row.appendChild(semesterCell);

        const academicYearCell = document.createElement("td");
        academicYearCell.textContent = course.academicYear;
        row.appendChild(academicYearCell);

        const creditCell = document.createElement("td");
        creditCell.textContent = course.credit;
        row.appendChild(creditCell);

        const totalCell = document.createElement("td");
        totalCell.textContent = course.total;
        row.appendChild(totalCell);

        const gradeCell = document.createElement("td");
        gradeCell.textContent = course.grade;
        row.appendChild(gradeCell);

        tableBody.appendChild(row);
    });
}